# Generated by Django 4.0.3 on 2022-03-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_location_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='currentLocation',
        ),
    ]
