# Generated by Django 4.0.3 on 2022-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_gpspings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='startLocation',
        ),
        migrations.AddField(
            model_name='trip',
            name='endLat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='endLng',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='startLat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='startLng',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
