# Generated by Django 4.0.3 on 2022-04-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_trip_startlocation_trip_endlat_trip_endlng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='endLat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='endLng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='endTime',
        ),
    ]
